# Generated by Django 4.0.4 on 2022-05-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('porcentaje', models.IntegerField(default=50)),
                ('pais', models.CharField(max_length=30)),
                ('universidad', models.CharField(max_length=40)),
                ('requerimientos', models.CharField(max_length=100)),
            ],
        ),
    ]
